AI-RAG-HTTP/manifest.json
@divyaswarnkar, @Elaina-Lee, @preetriti1: Please review and merge, thanks!
=> RAG - HTTP template: Edit pass on metadata, parameter display names, and descriptions 

AI-RAG-OneDriveforBusiness/manifest.json, AI-RAG-OneDriveforBusiness/workflow.json
=> RAG - OneDrive for Business template: Edit pass on metadata, parameter display names, and descriptions

AI-RAG-SFTP/manifest.json, AI-RAG-SFTP/workflow.json
=> RAG - SFTP template: Edit pass on metadata, parameter display names, and descriptions 

AI-RAG-for-Images/manifest.json, AI-RAG-for-Images/workflow.json
Q: The template includes an Azure Files connection. Are customers supposed to use Azure Files for storing their image?
A: Nevermind, I saw the note in the workflow.json that you can replace Azure Files with a different action to get the image.
=> RAG - Images template: Edit pass on metadata, parameter display names, and descriptions

DesignPattern-RequestResponse/manifest.json, DesignPattern-RequestResponse/workflow.json
=> DesignPattern-RequestResponse template: Edit pass on metadata, parameter display names, and descriptions 

DesignPattern-TryCatch/manifest.json, DesignPattern-TryCatch/workflow.json
=> DesignPattern-TryCatch template: Edit pass on metadata, parameter display names, and descriptions 

AI-RAG-Sharepoint/manifest.json
=> RAG - SharePoint: Consistency edit

IBMMQQueueBrowseLockAbort/manifest.json, IBMMQQueueBrowseLockAbort/workflow.json
=> IBM MQ queue template: Edit pass on metadata, parameter display names, and descriptions

SAP-SalesOrder-Synch-Azure-OData/manifest.json
=> SAP-OData: Synch sales order template: Edit pass on metadata, parameter display names, and descriptions

ServiceBusQueueLockTokenRenewal/manifest.json, ServiceBusQueueLockTokenRenewal/workflow.json
=> Azure Service Bus queue peek-lock-token template: Edit pass on metadata, parameter display names, and descriptions

ServiceBusQueuePeekLockAbandon/manifest.json, ServiceBusQueuePeekLockAbandon/workflow.json
=> Azure Service Bus queue peek-lock-abandon template: Edit pass on metadata, parameter display names, and descriptions 

ServiceBusTopicLockTokenRenewal/manifest.json, ServiceBusTopicLockTokenRenewal/workflow.json
=> Azure Service Bus topic subscription peek-lock-token template: Edit pass on metadata, parameter display names, and descriptions

ServiceBusTopicPeekLockAbandon/manifest.json, ServiceBusTopicPeekLockAbandon/workflow.json
=> Azure Service Bus topic subscription peek-lock-abandon template: Edit pass on metadata, parameter display names, and descriptions 

SAP-BusinessPartner-Synch-Sharepoint-OData/manifest.json, SAP-BusinessPartner-Synch-Sharepoint-OData/workflow.json
@divyaswarnkar, @Elaina-Lee, @preetriti1:
In the workflow.json file, I had trouble understanding the following string. Please share what the resolved string should look like?
`Loop limit hit (@{add(div(variables('totalCountOfSAPBusinessPartners'),variables('odataTopValue')),1)} needed, current: @{parameters('loopLimit_#workflowname#')})! Adjust $top (@{variables('odataTopValue')}) or raise loop limit (max 5000!).`
=> SAP-OData: Synch business partners template: Edit pass on metadata, parameter display names, and descriptions 

package-lock.json, package.json, patch_template_variables.js
Anybody adding a template can now run the below on their template folder once it is completed to automatically suffix the #workflowName# in their names.
`npm run patchTemplate [folder1] [folder2] ...`
where [folder1] and [folder2] are the new template folders.
=> Adding script file to update parameters and connections name

patch_template_variables.js
[Command line output example]
* No change is made for single-workflow
[New features]
- Running the command to the multi-workflow main folder will run updating #workflowname# for all nested folders
- Main manifest connections will be updated with the gathered connections of nested folders
- Verifies if connections with the same key and/or parameters with the same name have different values
- Main manifest featuredOperations will be updated with the gathered featuredOperations of nested folders
Running 1 multi-workflow template folder
- example command: `npm run patchTemplate sample-accelerator-1`
1) Success case (main manifest connections will be automatically updated:
> ------------Starting patching templates with suffix------------
[Multi-workflow patch start] Patching parameter and …
=> Updating script for Connections / Parameters / FeaturedOperation Verify + Combine Update

get-sales-order-status-sap-teams-bapi/workflow.json, post-sap-goodsmovement-using-bapi/workflow.json, sync-business-partner-sap-sharepoint-odata/workflow.json, sync-sales-order-sap-blob-storage-odata/workflow.json, unblock-user-sap-teams-self-service-bapi/workflow.json
Some workflow.json has extra field of definition wrapping workflowDefinition with kind. This is blocking correct workflow generation.
=> Fixed workflows in templates with "definitions"

.github/workflows/codeql-analysis.yml
Adding codeql workflow to the repo
=> Adding codeql workflow to the repo

vectorize-onedrive-aisearch-request/manifest.json, vectorize-onedrive-aisearch-schedule/manifest.json, vectorize-onedriveforbusiness-aisearch-request/manifest.json, vectorize-onedriveforbusiness-aisearch-schedule/manifest.json
@Elaina-Lee & @divyaswarnkar for review
=> Content QA edits for new vectorize workflow templates

patch_template_variables.js
- updated patch template script according to the restructured template repo format
- Note: featuredConnectors is up to the author, and is not automatically generated
=> Patch template script for restructured template format
